### ISSUE TITLE
Migration 0001 imports non-existent method

### ISSUE THREAD

**Issue by mik3y** [stephenmcd/cartridge#95]
Looks like commit 832032f739061579a4d9dc0b4e7e7c10f67ed78f broke south migration 0001:

```
$ manage.py migrate
[...]
  File "/home/ubuntu/.virtualenvs/pkb/local/lib/python2.7/site-packages/South-0.7.6-py2.7.egg/south/migration/migrators.py", line 175, in _run_migration
    migration_function()
  File "/home/ubuntu/.virtualenvs/pkb/local/lib/python2.7/site-packages/South-0.7.6-py2.7.egg/south/migration/migrators.py", line 57, in <lambda>
    return (lambda: direction(orm))
  File "/home/ubuntu/.virtualenvs/pkb/local/lib/python2.7/site-packages/Cartridge-0.8.1-py2.7.egg/cartridge/shop/migrations/0001_initial.py", line 233, in forwards
    from cartridge.shop.management import create_initial_product
ImportError: cannot import name create_initial_product
```

Maybe just a matter of renaming the method, though IMO it'd be better still to avoid sneaking this hook into the migration (introduced in 52fa3f70086fc56e4718bb33c36f137508f2d684).  In addition to making the migration brittle to external changes as above, the forced prompt interferes with non-interactive `migrate` (deployment scripts, continuous builds, etc).
